[versions]
coreKtx = "1.13.1"
gson = "2.11.0"
mmkv = "1.3.9"

[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
mmkv = { module = "com.tencent:mmkv", version.ref = "mmkv" }